spring:
  application:
    name: tihu-backend
  datasource:
    url: jdbc:mysql://202.194.14.120:3306/java_3_14?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: java_3_14
    password: JavaP314@
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0

server:
  servlet:
    context-path: /
  port: 22224

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

sa-token:
  token-name: Authorization
  timeout: 86400
  active-timeout: -1
  is-concurrent: false
  is-share: false
  token-style: uuid
  is-log: true
